Improve regexs for ssh configuration
dblenkus/ansible-common pull request #4
Opened 2017-01-01 22:17 UTC by dblenkus

2017-01-10 15:45 UTC, tjanez requested changes
Otherwise, looks good.

I've tested it on CentOS 7.2 and RHEL 7.2 and it works.

2017-01-10 15:45 UTC, tjanez commented on tasks/security.yml
> +    regexp: "^(#\s*)?PasswordAuthentication\s+(yes|no)"
You need to escape `\` with another `\`. The regexp should be:
```
"^(#\\s*)?PasswordAuthentication\\s+(yes|no)"
```

2017-01-10 15:45 UTC, tjanez commented on tasks/security.yml
> +    regexp: "^(#\s*)?PermitRootLogin\s+(yes|no)"
Same here.

2017-01-11 18:45 UTC, dblenkus commented
Fixed

2017-01-12 10:14 UTC, tjanez approved these changes

2017-01-12 13:34 UTC, merged